services:
  node-app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=80
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: